# Generated by Django 4.0.5 on 2022-07-21 08:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0002_notification_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='acceptAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
