# Generated by Django 4.0.5 on 2022-07-21 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0003_notification_accept_notification_acceptat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='accept',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='acceptAt',
        ),
    ]
