version: '2'
services:
  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - /www/static/
    volumes_from:
      - web
    links:
      - web:web
    depends_on:
      - web
  web:
    restart: always
    build: .
    expose:
      - "8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: uwsgi --http :8000 --module ShareDocument.wsgi
    volumes:
      - .:/code
