version: '2'
services:
  nginx:
    container_name: nginx
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - /www/static/
    volumes_from:
      - web
    links:
      - web:web
    depends_on:
      - web
  web:
    container_name: web
    restart: always
    build: .
    expose:
      - "8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: uwsgi --http :8000 --module ShareDocument.wsgi
    volumes:
      - .:/code
    depends_on:
      - db

  db:
    container_name: db
    restart: always
    image: postgres
    environment:
      - POSTGRES_DB=sharedocument
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=nghiem@123
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - ../data:/var/lib/postgresql/data
