version: '2'
services:
  nginx:
    container_name: nginx
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - frontend_volume:/frontend
      - backend_volume:/code
    depends_on:
      - frontend
      - web

  web:
    container_name: web
    restart: always
    build: .
    expose:
      - "8000"
    ports:
      - "8000:8000"
    env_file:
      - .env.production.local
    command: uwsgi --http :8000 --module ShareDocument.wsgi
    volumes:
      - backend_volume:/code
    depends_on:
      - db_production

  db_production:
    container_name: db_production
    restart: always
    image: postgres
    environment:
      - POSTGRES_DB=sharedocument
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=nghiem@123
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - ../data:/var/lib/postgresql/data

  frontend:
    container_name: frontend
    restart: always
    build: ./templates/
    volumes:
      - frontend_volume:/frontend
    depends_on:
      - web
    tty: true

  redis:
    container_name: redis
    restart: always
    image: redis
    expose:
      - 6379

volumes:
  frontend_volume:
  backend_volume:
