# Generated by Django 4.0.5 on 2022-07-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='price',
        ),
        migrations.AddField(
            model_name='document',
            name='review_img',
            field=models.FileField(default='logo1.png', upload_to='document/%Y/%m/%d/review'),
        ),
        migrations.DeleteModel(
            name='DocumentUser',
        ),
    ]
