# Generated by Django 4.0.5 on 2022-06-27 02:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0004_delete_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='document_file/%Y/%m/%d')),
                ('num_download', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Document.category')),
            ],
        ),
    ]
