# Generated by Django 4.0.5 on 2022-07-14 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0004_document_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='num_download',
            new_name='view',
        ),
    ]
