# Generated by Django 4.0.5 on 2022-07-29 14:04

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('25ce7481-3084-44e7-9f6a-8edbc174be1f'), primary_key=True, serialize=False, unique=True)),
                ('createAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('question', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('8fad9e6f-5527-42ee-a013-227e9b045eeb'), primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('1e003faa-9573-4277-a3d6-dcb6a6dbeeb1'), primary_key=True, serialize=False, unique=True)),
                ('inputs', models.TextField()),
                ('outputs', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coding.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coding.language'),
        ),
    ]
