# Generated by Django 4.0.5 on 2022-07-29 14:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Coding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a4c5f042-994a-46e0-b86e-77abe1563d0a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='id',
            field=models.UUIDField(default=uuid.UUID('32f8017d-ba7f-4383-aecd-07a3e32bb10e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8e6a6170-2301-42b7-81cf-206933430c2d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
