# Generated by Django 4.0.5 on 2022-07-20 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0002_notification_otheruser_alter_notification_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
