# Generated by Django 4.0.5 on 2022-07-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_post_review_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='introduce',
            field=models.TextField(default='Introduce'),
        ),
    ]
