# Generated by Django 4.0.5 on 2022-07-23 06:44

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_post_search_vector_post_blog_post_search__47a33e_gin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(default=django.contrib.postgres.search.SearchVector('content'), null=True),
        ),
    ]
