# Generated by Django 4.0.5 on 2022-07-14 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0003_remove_document_price_document_review_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='slug',
            field=models.SlugField(blank=True, default='slug', max_length=255),
        ),
    ]
