# Generated by Django 4.0.5 on 2022-07-21 05:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0005_rename_num_download_document_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
