# Generated by Django 4.0.5 on 2022-07-08 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Introduce',
        ),
    ]
