# Generated by Django 4.0.5 on 2022-07-08 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_post_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='review_image',
            field=models.FileField(default='Facebook_Embed.png', upload_to='review_post_img'),
        ),
    ]
