# Generated by Django 4.0.5 on 2022-06-30 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0018_alter_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
