# Generated by Django 4.0.5 on 2022-07-21 08:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0003_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='acceptAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
